name: Update Express Entry Data

on:
  schedule:
    # Run daily at 9 AM UTC (4 AM EST, 5 AM EDT)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
        
    - name: Run data update script
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_FROM_EMAIL: ${{ secrets.SMTP_FROM_EMAIL }}
        SMTP_TO_EMAIL_TEST: ${{ secrets.SMTP_TO_EMAIL_TEST }}
      run: |
        cd Data
        python automation.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Data/analysis.json
        git add Data/EE.json
        git add Data/EE.csv
        git diff --staged --quiet || git commit -m "Auto-update Express Entry data [skip ci]"
        git push
